server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的指责就是维护实例，并不需要去检索实例
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #是指于eureka Server交互的地址查询服务
       defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
