server:
  port: 80

#负载均衡时需配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: false
